# Set the build language to Python
language: python

# Set the python version to 3.6
python: 3.6

before_install:
    - bash install-spot.sh
    - export PYTHONPATH="$HOME/.local/lib/python3.6/site-packages":"$PYTHONPATH"

# Run the unit test
script:
    - bash gen-parser.sh
    - python3 -m unittest discover

